#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct Particle {
    vec2 pos;
    vec2 vel;
    vec4 color;
};

layout(std430, binding = 0) buffer ParticleBuffer {
    Particle particles[];
};

uniform float uDeltaTime;
uniform vec2 uMousePos; 
uniform float uTime;

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= particles.length()) return;

    vec2 pos = particles[id].pos;
    vec2 vel = particles[id].vel;

    vec2 dir = uMousePos - pos; 
    float dist = length(dir);
    
    float strength = 0.5 / (dist + 0.1); 
    vec2 force = normalize(dir) * strength;

    //if (dist > 0.5) force *= 0.0; 

    vel += force * u_DeltaTime;
    vel *= 0.98; // Friction pour stabiliser
    pos += vel * u_DeltaTime;

    particles[id].pos = pos;
    particles[id].vel = vel;
    
    particles[id].color = vec4(0.5 + (pos.x * 0.5), 0.2, 0.8 + (dist * 0.5), 1.0);
}